version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: semantikabadi
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    ports:
      - "6334:6334"
    volumes:
      - semantikabadi_data:/qdrant/storage

volumes:
  semantikabadi_data:
