name: Deploy SemantikAbadi

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          cat <<EOF > .env
          QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
          EOF

      - name: Prepare deploy files
        run: |
          mkdir semantikabadi
          mv docker-compose.yml .env semantikabadi/

      - name: Copy files to Wiwokdetok Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "semantikabadi/*"
          target: "~/"

      - name: Run on Wiwokdetok Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/semantikabadi || exit 1
            docker-compose down || true
            docker-compose up -d
